approvedGitRepositories:
    - "**"

enableScripts: true

nodeLinker: node-modules

packageExtensions:
    "react-colorful@5.8.1":
        peerDependenciesMeta:
            react:
                optional: true
            react-dom:
                optional: true

npmMinimalAgeGate: 0
